### PR TITLE
Change whitespace naming with cammelCase naming

### PR DESCRIPTION
**Pull request by antonio-ivanovski**
There is bit different case sensitivity and whitespace sensitivity in the Mac and Linux file systems, this was causing build to fail on some machines. camelCase is more common and it is handled better by webpack other build systems.

Here is the error I was getting
```ts
ERROR in ./node_modules/input-format/index.js 1:0-5:32
Module not found: Error: Can't resolve './modules/template parser' in '/root/.cache/bazel/_bazel_root/37a2adbff33fccdf1d0fe391e6580e3e/sandbox/linux-sandbox/43/execroot/project/node_modules/input-format'
 @ ./node_modules/@project/ui-kit/build/components/phoneNumberPicker/index.js 8:23-46
 @ ./node_modules/@project/ui-kit/build/components/index.js 35:21-51
 @ ./node_modules/@project/ui-kit/build/index.js 15:21-44
 @ ./packages/application/frontend/src/App.tsx 4:0-45 9:28-34 11:28-34 14:28-34
 @ ./packages/application/frontend/src/main.tsx 3:0-28 18:32-35
```

There are no changes in the logic whatsoever, only changes in the names of files and their imports.

Shouldn't cause breaking changes to users since this is just the folder rename. The exports remains the same.

### CODE REVIEW

**Comment by catamphetamine** [comment]
@toteto Ok, thanks. I used to dislike camelCase in the past but then I've agreed to make my projects in camelCase, just didn't get to renaming this one because it's no longer in development. Merging.

**Comment by catamphetamine** [comment]
Oh, turns out the main repo is not GitHub anymore, it's GitLab.

**Comment by catamphetamine** [comment]
@toteto Looks like the pull request will have to be re-done there:
https://gitlab.com/catamphetamine/input-format/
When you have time.

**Comment by antonio-ivanovski** [comment]
@catamphetamine oh yes, maybe you should archive this repository so people are not led to the wrong one?

**Comment by antonio-ivanovski** [comment]
> @toteto Looks like the pull request will have to be re-done there:
> https://gitlab.com/catamphetamine/input-format/
> When you have time.

The issue with the namings are fixed, no need to re-do-it

**Comment by catamphetamine** [comment]
> maybe you should archive this repository so people are not led to the wrong one?

Archiving a repository seems to make it read-only and I still use GitHub as a backup for storing repo snapshots.

> The issue with the namings are fixed, no need to re-do-it

Yeah, I mean, you could redo it on GitLab.

**Pull request merged**
